package com.seatflow.booking.domain;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import org.hibernate.annotations.UuidGenerator;

import java.security.SecureRandom;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * A confirmed sale. Terminal: seats in a booking never return to the pool.
 * <p>
 * The identifier is generated by Hibernate on persist, not assigned in the
 * constructor. An assigned id makes Spring Data treat a brand-new entity as an
 * existing one, so {@code save} issues a merge - a SELECT and an UPDATE instead
 * of an INSERT - and {@code @PrePersist} never runs. Callers read the id after
 * flushing, which is when the seats can be stamped with it.
 */
@Entity
@Table(name = "bookings")
public class Booking {

    /** Unambiguous alphabet: no O/0, no I/1. People read these aloud. */
    private static final String REFERENCE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
    private static final int REFERENCE_LENGTH = 8;
    private static final SecureRandom RANDOM = new SecureRandom();

    @Id
    @UuidGenerator
    private UUID id;

    @Column(name = "reservation_id", nullable = false)
    private UUID reservationId;

    @Column(name = "payment_id", nullable = false)
    private UUID paymentId;

    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @Column(name = "event_id", nullable = false)
    private UUID eventId;

    @Column(name = "booking_reference", nullable = false)
    private String bookingReference;

    @Column(name = "total_cents", nullable = false)
    private long totalCents;

    @Column(nullable = false)
    private String currency = "INR";

    @Column(nullable = false)
    private String status = "CONFIRMED";

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    /** Read-only join column: booking_id is part of BookingSeat's own key. */
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "booking_id", insertable = false, updatable = false)
    private List<BookingSeat> seats = new ArrayList<>();

    protected Booking() {
        // for JPA
    }

    public static Booking confirm(
            UUID reservationId, UUID paymentId, UUID userId, UUID eventId, long totalCents) {

        Booking booking = new Booking();
        booking.reservationId = reservationId;
        booking.paymentId = paymentId;
        booking.userId = userId;
        booking.eventId = eventId;
        booking.totalCents = totalCents;
        booking.bookingReference = generateReference();
        return booking;
    }

    private static String generateReference() {
        StringBuilder reference = new StringBuilder(REFERENCE_LENGTH);
        for (int i = 0; i < REFERENCE_LENGTH; i++) {
            reference.append(REFERENCE_ALPHABET.charAt(RANDOM.nextInt(REFERENCE_ALPHABET.length())));
        }
        return reference.toString();
    }

    /**
     * Records the seats sold. Each row is also the thing
     * {@code uq_booking_seat_once} checks, so this is where a second sale of the
     * same seat would be refused by the database.
     */
    public void recordSeats(List<SoldSeat> sold) {
        sold.forEach(seat -> seats.add(new BookingSeat(id, seat.eventSeatId(), seat.priceCents())));
    }

    @PrePersist
    void onCreate() {
        this.createdAt = Instant.now();
    }

    public UUID getId() {
        return id;
    }

    public UUID getReservationId() {
        return reservationId;
    }

    public UUID getPaymentId() {
        return paymentId;
    }

    public UUID getUserId() {
        return userId;
    }

    public UUID getEventId() {
        return eventId;
    }

    public String getBookingReference() {
        return bookingReference;
    }

    public long getTotalCents() {
        return totalCents;
    }

    public String getCurrency() {
        return currency;
    }

    public String getStatus() {
        return status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public List<BookingSeat> getSeats() {
        return Collections.unmodifiableList(seats);
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof Booking booking)) {
            return false;
        }
        return id != null && id.equals(booking.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "Booking[" + bookingReference + "]";
    }

    /** A seat sold, at the price the customer was quoted. */
    public record SoldSeat(UUID eventSeatId, long priceCents) {
    }
}
